server:
  port: 8081

security.jwt.token.secret-key: my-secret-key

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1093359169270-116eohrstdabjcbafhd143q44elr4i9f.apps.googleusercontent.com
            clientSecret: NnPZphepJY6qwC_94okz1FId
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - emails
              - public_profile

app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect